from unittest_reinvent.running_modes.curriculum_tests.test_manual_curriculum_learning import \
    TestManualCurriculumLearning

from unittest_reinvent.running_modes.curriculum_tests.test_automated_curriculum_learning import \
    TestAutomatedCurriculumLearning
from unittest_reinvent.running_modes.curriculum_tests.test_no_curriculum_molformer import TestNoCurriculumMolformer
from unittest_reinvent.running_modes.curriculum_tests.test_molformer_curriculum_learning import \
    TestMolformerCurriculumLearning
